### ISSUE TITLE
[Critical] Private images

### ISSUE THREAD

**Issue by Timdnb** [REMLA24-Team-5/operation#47]
Not sure if this is still the case, but we got a couple of peer feedbacks that they couldn't pull the images because they were private

@SagaRut is there a setting you can change such that people outside of the organisation can pull them

**Comment by SagaRut** [comment]
Both app and model-service are public packages
![image](https://github.com/REMLA24-Team-5/operation/assets/66416165/88257904-0067-45ad-94e0-cfbdfd362a9f)

**Comment by Timdnb** [comment]
Okay, then we should be good, ill close the issue
