### ISSUE TITLE
Setup a multi-node VM setup with Vagrant

### ISSUE THREAD

**Issue by SagaRut** [REMLA24-Team-5/operation#7]
The setup requires one control node (we recommend 1 core, 4+GB memory) that will later run the Kubernetes controller and two Kubernetes worker nodes (we recommend 2 cores and 6+GB memory each) that are registered with the controller. The number of provisioned workers should be configurable through a variable in the Vagrantfile to make it easy to scale (up or down).

To make it easy to distinguish the different VMs, call them controller and node<N> .

The virtual machines have been automatically created with the required spec. It is possible to get
some CLI access, e.g., via vagrant ssh . It is possible to communicate with the provisioned VMs at
the very least through port-forwarding.

**Comment by Timdnb** [comment]
Started a branch for this
